feat: add endpoints
Team-Strawberry-CC36/backend pull request #11
Opened 2024-11-24 07:04 UTC by ai-n0808

Added these endpoints.
<Places>
- GET /places : Retrieves the Place interfaced object, no just ‘Places table rows’
- POST /places : Add a new place to the database
- PATCH /places/:id : Update the details of a specific place.
- DELETE /places/:id : Remove a place by its ID.

<Experiences>
- POST /places/:id/experiences : Add a new experience for a specific place.
- PATCH /places/:id/experiences/:expId Update details of a specific experience by its ID.
- DELETE /places/:id/experiences/:expId : Remove an experience by its ID.

2024-11-24 07:06 UTC, ai-n0808 commented
@brianaqp 
Please let me know if you have any thought or feedback for this.

2024-11-24 11:02 UTC, ai-n0808 commented
Now If I test endpoints in postman, I got error with endpoints of experiences. 
All of places endpoints are all good.

2024-11-24 11:22 UTC, brianaqp requested changes
Everything looks fine, perfect. Just delete the unused endpoints, and later we test

2024-11-24 11:22 UTC, brianaqp commented on src/router/index.ts
> +    res.json(places);
For know its ok, it doesn't have the Place Interface structure, but its very close

2024-11-24 11:22 UTC, brianaqp commented on src/router/index.ts
> +router.post("/places", async (req: Request, res: Response) => {
We are not going to use this, most likely in the entire project

When we add the feature of "add your own place" we can implemented, but for now, removed

Places are seed it manually, or by admin

2024-11-24 11:22 UTC, brianaqp commented on src/router/index.ts
> +//Update details of specific place
The same, we are not gonna used this

2024-11-24 11:22 UTC, brianaqp commented on src/router/index.ts
> +router.patch("/places/:id", async (req: Request, res: Response) => {
Delete it

2024-11-24 11:22 UTC, brianaqp commented on src/router/index.ts
> +router.delete("/places/:id", async (req: Request, res: Response) => {
Delete

2024-11-24 11:22 UTC, brianaqp commented on src/router/index.ts
> +router.post("/places/:id/experiences", async (req: Request, res: Response) => {
Looks nice. 👍 we need to test it later

2024-11-24 11:22 UTC, brianaqp commented on src/router/index.ts
> +);
Nice +1

2024-11-24 11:22 UTC, brianaqp commented on src/router/index.ts
> +
Nice +1

2024-11-25 05:17 UTC, brianaqp approved these changes

2024-11-25 05:18 UTC, merged